### ISSUE TITLE
Acquisitions

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#254]
This issue is a container to reference the various classes proposed as issues themselves, pertinent to implementing the Acquisitions portion of ISO 19115-2 2019, and the 2022 Amdt.

Classes:

- [ ] adiwg/mdJSON-schemas#212
- [ ] adiwg/mdJSON-schemas#219
- [ ] adiwg/mdJSON-schemas#215
- [ ] adiwg/mdJSON-schemas#218
- [ ] adiwg/mdJSON-schemas#217
- [ ] adiwg/mdJSON-schemas#216
- [ ] adiwg/mdJSON-schemas#213
- [ ] adiwg/mdJSON-schemas#214
- [ ] adiwg/mdJSON-schemas#220
- [ ] adiwg/mdJSON-schemas#221

**Comment by jwaspin** [comment]
Updated original comment: Platform was listed twice, just removed the duplicate
