### ISSUE TITLE
Data Quality

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#256]
This issue is a container to reference the various classes proposed as issues themselves, pertinent to implementing Data Quality as defined in ISO 19157 2013, and the 2018 Amdt.

Classes:

- [ ] adiwg/mdJSON-schemas#223
- [ ] adiwg/mdJSON-schemas#230
- [ ] adiwg/mdJSON-schemas#224
- [ ] adiwg/mdJSON-schemas#225
- [ ] adiwg/mdJSON-schemas#226
- [ ] adiwg/mdJSON-schemas#229
- [ ] adiwg/mdJSON-schemas#228
- [ ] adiwg/mdJSON-schemas#227
- [ ] adiwg/mdJSON-schemas#255
- [ ] Complete items identified in #262

**Comment by jwaspin** [comment]
#262 related?
