### ISSUE TITLE
Feature/Data Quality

### ISSUE THREAD

**Issue by dwalt** [adiwg/mdJson-schemas#262]
- [ ] Missing asterisks for required elements - review schema issues
- [ ] Missing element definitions - review schema issues
- [ ] Order of Report elements should follow that outlined in Report schema issue #224 
- [ ] Evaluation Method is not an array
- [ ] Quality Measure: either a name or identifier are required
- [ ] Translator UI not working, network error
- [ ] Type element is missing, required to identify the standard report (see issue #224)

**Comment by jwaspin** [comment]
Was PR #261 sufficient to close this?

**Comment by jwaspin** [comment]
@dwalt 

The following will be fix in PR #269 
- Order of Report elements
- Evaluation Method is not an array

**Comment by jwaspin** [comment]
@dwalt 

`Translator UI not working, network error` does not seem to be related to mdJson-schemas, should this be in here?

`Scope is required` Does this apply to everywhere scope exists within data quality? (based on them all being single objects and not an array, they are all already limited to only one, but none of the schemas indicate the scope is required)

**Comment by jwaspin** [comment]
What I've done:

- [x] Missing asterisks for required elements - review schema issues
- [ ] Missing element definitions - review schema issues
- [x] Order of Report elements should follow that outlined in Report schema issue #224 
- [x] Evaluation Method is not an array
- [x] Quality Measure: either a name or identifier are required
- [ ] Translator UI not working, network error
- [x] Type element is missing, required to identify the standard report (see issue #224)
- [ ] Scope is required, max of one

**Comment by jwaspin** [comment]
It mentions "Translator UI not working, network error" but I'm not sure what this refers to. If I were to guess, this is actually an issue in mdTools, not mdJson-schemas, because that translator UI is not working, but there's [already an issue for that](https://github.com/adiwg/mdTools/issues/14) in the mdTools repository.

**Comment by dwalt** [comment]
@jwaspin I would agree, I believe this was an artifact of previous Data Quality testing identifying that translation of DQ could not be tested.
